### PR TITLE
Added team app

### PR DESCRIPTION
**Pull request by Kraniket901**
created django app team.
added the app to settings.py
created urls.py under team app
included team/urls.py in the server/urls.py with prefix api/team/

### CODE REVIEW

**Comment by sahil9001** [comment]
Pull the latest changes and resolve conflicts.

**Comment by Kraniket901** [comment]
- in server/settings.py comma is missing at one place. (after 'questions')
- in server/urls.py commas are missing at two places. (after include('users.urls')) and after include('questions.urls')) )

I've made the changes. Should i click "Commit Merge" after resolving conflicts as show below?

Screenshot from 2022-10-29 01-29-42

**Comment by Kraniket901** [comment]
The latest server/settings.py file is missing comma in line 41. I can't resolve conflict either way, after adding it as well as without adding it.

Latest File:
Screenshot from 2022-10-29 10-53-51

My File after adding comma (showed Conflict) :
Screenshot from 2022-10-29 10-55-44

My File without adding comma (Again showed Conflict) :
Screenshot from 2022-10-29 10-58-02

**Comment by sahil9001** [comment]
Learn to pull the latest changes from upstream dev, "git fetch" then "git pull origin dev" (if you have origin remote else use upstream)

**Pull request closed without merging**
